#ifndef ENUMS_H
#define ENUMS_H
namespace Messages
{
  enum MESSAGE {HELLO_SERVER = 1, MESSAGE_RECEIVED, IS_SERVER_LOST, CLIENT_LOST, OPPONENT_INF, MY_INF,
                MOVE, BACK_MOVE, GO_TO_HISTORY, NEW_GAME, FROM_FILE, OPPONENT_INF_REQUEST, MY_INF_REQUEST,
                SERVER_LOST, SERVER_HERE, OPPONENT_LOST};
}
#endif // ENUMS_H
