#ifndef ENUMS_H
#define ENUMS_H
namespace Messages
{
  enum MESSAGE {HELLO_SERVER = 1, MESSAGE_RECEIVED, IS_SERVER_LOST, CLIENT_LOST, OPPONENT_INF, MY_INF, LOGIN,
                MOVE, BACK_MOVE, GO_TO_HISTORY, NEW_GAME, FROM_FILE, INF_REQUEST, SERVER_LOST, SERVER_HERE, OPPONENT_LOST};
}
#endif // ENUMS_H
